version: '3'

services:
  server:
    build: server
    command: ["run.py"]
    volumes:
      - ./server:/server
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    networks: 
      - former
    ports:
      - "4000:4000"

  client:
    build: client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    networks: 

      - former
    ports:
      - '3000:3000'
    links:
      - server
    depends_on:
      - server

volumes:
  node-modules:

networks:
    former:
        driver: bridge
